dir.files=D:\\MyMind\\files\\
dir.images=D:\\MyMind\\images\\
dir.deleteImages=D:\\MyMind\\deleteImages\\
dir.recent_files=D:\\MyMind\\recent_files
dir.shortcuts=D:\\MyMind\\config\\shortcuts.config
dir.notes=D:\\MyMind\\notes
# 打成jar包后，不能修改内部的配置文件，所以记录在外部
dir.css.properties=D:\\MyMind\\config\\css.properties