directory.images=D:\\MyMind\\images\\
directory.files=D:\\MyMind\\files\\
directory.recent_files=D:\\MyMind\\recent_files
directory.shortcuts=D:\\MyMind\\config\\shortcuts.config

#styleWheel=/fxml/style-wheel-polygon.fxml
styleWheel=/fxml/style-wheel-arc.fxml